name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TF_VAR_lambda_role_name: IventLambdaRole
      TF_VAR_github_actions_role_name: IventGithubActionsRole
      TF_VAR_events_table_arn: arn:aws:dynamodb:us-east-1:533267197673:table/Events
      TF_VAR_subscriptions_table_arn: arn:aws:dynamodb:us-east-1:533267197673:table/Subscriptions
      TF_VAR_events_table_stream_arn: arn:aws:dynamodb:us-east-1:533267197673:table/Events/stream/*
      TF_VAR_github_repo: ankurshashwat/ivent
      TF_VAR_test_username: ${{ secrets.TEST_USERNAME }}
      TF_VAR_test_password: ${{ secrets.TEST_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267197673:role/IventGithubActionsRole
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: ./terraform
